FROM node:24-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_API_SERVER=http://localhost:8000
ENV VITE_API_SERVER=$VITE_API_SERVER
EXPOSE 3000
CMD ["node_modules/.bin/vite", "--host", "0.0.0.0"]
