// Generated by Skyramp v1.3.40 on 2026-08-29 22:24:41.881325 -0700 PDT m=+1027.091961293
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dashboard_trophies_card_category.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/dashboard_trophies_card_category_v2_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/login`);
    await page.goto(`${baseUrl}/en/dashboard`);

    const trophiesWidget = page.locator('.MuiCard-root, .MuiPaper-root').filter({ hasText: 'Trophies' });
    await expect(trophiesWidget).toHaveCount(1);
    await expect(trophiesWidget.getByRole('heading')).toHaveText('Nothing here yet...');

    await expect(page.locator('.MuiChip-label')).toHaveCount(0);

    expect(pageErrors).toHaveLength(0);
});
