# Generated by Skyramp v1.3.40 on 2026-08-30 10:01:19.669009 -0700 PDT m=+586.639479168
# Command: skyramp generate contract rest http://localhost:8000/api/v2/ingredient-info/ \
# 		--api-schema http://localhost:8000/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--provider-output ingredient_info_batch_id_filter_contract_test.py \
# 		--query-params id__in=1 \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v2/ingredient-info/ GET
def test_ingredient_info_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_ingredient_info_GET_response_body = r'''{
        "count": 123,
        "results": [
            {
                "carbohydrates": "string",
                "created": "2026-08-30T10:01:19-07:00",
                "energy": 0,
                "fat": "string",
                "id": 0,
                "image": {
                    "created": "2026-08-30T10:01:19-07:00",
                    "height": 0,
                    "id": 0,
                    "image": "string",
                    "ingredient_id": 0,
                    "ingredient_uuid": "string",
                    "last_update": "2026-08-30T10:01:19-07:00",
                    "size": 0,
                    "uuid": "de7717ef-1850-476f-a597-f4ec42a20fc5",
                    "width": 0
                },
                "language": {
                    "full_name": "string",
                    "full_name_en": "string",
                    "id": 0,
                    "short_name": "string"
                },
                "last_imported": "2026-08-30T10:01:19-07:00",
                "last_update": "2026-08-30T10:01:19-07:00",
                "license": {
                    "full_name": "string",
                    "id": 0,
                    "short_name": "string"
                },
                "name": "string",
                "protein": "string",
                "thumbnails": {
                    "medium": "string",
                    "small": "string"
                },
                "uuid": "41ca48d0-ca49-4eaf-a66a-c4a4a4a06f99",
                "weight_units": [
                    {
                        "gram": 0,
                        "id": 0,
                        "ingredient": 0,
                        "name": "string",
                        "uuid": "da59ac9e-f39e-484d-aea6-9a2ee85ff1b4"
                    }
                ]
            }
        ]
    }'''

    # Execute Request
    ingredient_info_GET_response = client.send_request(
        url=URL,
        path="/api/v2/ingredient-info/",
        method="GET",
        headers=headers,
        query_params={"id__in": "1"}
    )

    # Generated Assertions
    assert ingredient_info_GET_response.status_code == 200
    assert skyramp.check_schema(ingredient_info_GET_response, r'''{"next": null, "previous": null}''')
    assert skyramp.get_response_value(ingredient_info_GET_response, "count") is not None
    assert skyramp.get_response_value(ingredient_info_GET_response, "count") >= 0
    assert skyramp.get_response_value(ingredient_info_GET_response, "count") == 0
    assert skyramp.get_response_value(ingredient_info_GET_response, "results.0") is None


if __name__ == "__main__":
    test_ingredient_info_get()
