# Generated by Skyramp v1.3.40 on 2026-08-28 22:51:06.423709 -0700 PDT m=+469.974110585
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output ingredient_info_rename_migration_walk_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp/scenario_ingredient_info_rename_migration_walk.json

# Import of required libraries
import skyramp
import os
import time

from SkyrampUtils import (
    get_ingredient_info_list,
    get_ingredientinfo_detail,
    get_ingredientinfo_list,
)


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")


def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    endpoint_2_GET_response = get_ingredientinfo_list(client, headers, expected_status=410)
    assert skyramp.get_response_value(endpoint_2_GET_response, "detail") == "This endpoint was renamed to ingredient-info."

    endpoint_3_GET_response = get_ingredientinfo_detail(client, headers, 1, expected_status=410)
    assert skyramp.get_response_value(endpoint_3_GET_response, "detail") == "This endpoint was renamed to ingredient-info."

    endpoint_1_GET_response = get_ingredient_info_list(client, headers, expected_status=200)
    assert skyramp.get_response_value(endpoint_1_GET_response, "detail") is None
    assert skyramp.check_schema(endpoint_1_GET_response, '{"next": null, "previous": null}')
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 0
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0") is None
    assert skyramp.check_schema(endpoint_1_GET_response, '{"count": 0, "next": null, "previous": null, "results": []}')


if __name__ == "__main__":
    test_integration()
