# Generated by Skyramp v1.3.40 on 2026-08-28 22:51:13.903878 -0700 PDT m=+477.454142293
# Command: skyramp generate contract rest http://localhost:8000/api/v2/ingredientinfo/{ingredient_id}/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output ingredientinfo_retired_detail_gone_contract_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--path-params ingredient_id=c6ad3eea-aef9-4332-bfe8-1ff16c21bbe8 \
# 		--provider \
# 		--provider-output ingredientinfo_retired_detail_gone_contract_test.py \
# 		--response-status-code 410 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os

from SkyrampUtils import get_ingredientinfo_detail


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v2/ingredientinfo/{ingredient_id}/ GET
def test_ingredient_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    ingredient_id = "c6ad3eea-aef9-4332-bfe8-1ff16c21bbe8"

    ingredient_id_GET_response = get_ingredientinfo_detail(
        client, headers, ingredient_id, expected_status=410
    )
    assert skyramp.get_response_value(ingredient_id_GET_response, "detail") == "This endpoint was renamed to ingredient-info."
    assert skyramp.check_schema(ingredient_id_GET_response, '{"detail": "This endpoint was renamed to ingredient-info."}')
    assert skyramp.get_response_value(ingredient_id_GET_response, "id") is None
    assert skyramp.get_response_value(ingredient_id_GET_response, "results") is None


if __name__ == "__main__":
    test_ingredient_id_get()
