# Generated by Skyramp v1.3.40 on 2026-08-30 10:02:05.999478 -0700 PDT m=+632.970109418
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output ingredient_info_payload_expands_related_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp/scenario_ingredient-info-payload-expands-related.json

# Import of required libraries
import skyramp
import os
import time

from SkyrampUtils import (
    get_ingredient_info_list,
    get_ingredient_list,
)


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    limit = "1"

    endpoint_1_GET_response = get_ingredient_info_list(client, headers, limit)

    assert skyramp.check_schema(endpoint_1_GET_response, r'''{"next": null, "previous": null}''')
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") >= 0
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 0
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0") is None

    endpoint_2_GET_response = get_ingredient_list(client, headers, limit)

    assert skyramp.check_schema(endpoint_2_GET_response, r'''{"next": null, "previous": null}''')
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") is not None
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") >= 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "results.0") is None
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") == skyramp.get_response_value(endpoint_1_GET_response, "count")


if __name__ == "__main__":
    test_integration()
