# Generated by Skyramp v1.3.40 on 2026-08-30 10:01:53.696047 -0700 PDT m=+620.666635168
# Command: skyramp generate contract rest http://localhost:8000/api/v2/ingredient-info/{id}/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--path-params id=999999999 \
# 		--provider \
# 		--provider-output ingredient_info_detail_route_resolves_contract_test.py \
# 		--response-data {"detail":"No Ingredient matches the given query."} \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v2/ingredient-info/{id}/ GET
def test_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "999999999"

    # Expected Response Body
    expected_id_GET_response_body = r'''{
        "detail": "No Ingredient matches the given query."
    }'''

    # Execute Request
    id_GET_response = client.send_request(
        url=URL,
        path="/api/v2/ingredient-info/{id}/",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert id_GET_response.status_code == 404
    assert skyramp.check_schema(id_GET_response, expected_id_GET_response_body)
    assert skyramp.get_response_value(id_GET_response, "detail") is not None
    assert skyramp.get_response_value(id_GET_response, "detail") == "No Ingredient matches the given query."
    assert skyramp.get_response_value(id_GET_response, "errors") is None


if __name__ == "__main__":
    test_id_get()
