// Generated by Skyramp v1.3.40 on 2026-08-29 22:51:29.105519 -0700 PDT m=+973.894228167
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output nutrition_plans_only_logging_filter.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/nutrition_plans_only_logging_filter_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1489000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: Error[] = [];
    page.on('pageerror', (error: Error) => errors.push(error));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(`${baseUrl}/en/nutrition/overview`);
    await page.getByRole("button", { name: "add" }).click();

    const playwrightRequest0: Record<string, any> = {"description": "Logging plan"};

    await page.locator("#description").fill(getValue(playwrightRequest0, "description"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/nutritionplan/**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);
    expect((await response0.json()).only_logging).toBe(true);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "add" }).click();

    const playwrightRequest1: Record<string, any> = {"description": "Planning only"};

    await page.locator("#description").fill(getValue(playwrightRequest1, "description"));
    await page.getByRole("switch", { name: "Only track calories. Check" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v2/nutritionplan/**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(201);
    expect((await response1.json()).only_logging).toBe(false);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("switch", { name: "Only plans used for logging" })).not.toBeChecked();
    await expect(page.getByRole("link", { name: "Planning only" })).toBeVisible();
    await expect(page.getByRole("link")).toHaveCount(2);

    await page.getByRole("switch", { name: "Only plans used for logging" }).click();

    await expect(page.getByRole("switch", { name: "Only plans used for logging" })).toBeChecked();
    await expect(page.getByRole("link")).toHaveCount(1);
    await expect(page.getByRole("link").nth(0)).toContainText("Logging plan");
    await expect(page.getByRole("link", { name: "Planning only" })).toBeHidden();

    await page.getByRole("switch", { name: "Only plans used for logging" }).click();

    await expect(page.getByRole("switch", { name: "Only plans used for logging" })).not.toBeChecked();
    await expect(page.getByRole("link")).toHaveCount(2);
    await expect(page.getByRole("link", { name: "Planning only" })).toContainText("Planning only");

    expect(errors).toHaveLength(0);
});
