// Generated by Skyramp v1.3.40 on 2026-08-28 18:09:40.71381 -0700 PDT m=+1053.682747334
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output nutrition_plan_only_logging_switch.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/nutrition_plan_only_logging_switch_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1589000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/login`);
    await page.goto(`${baseUrl}/en/nutrition/overview`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(baseUrl);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(`${baseUrl}/en/nutrition/overview`);
    await page.getByRole("button", { name: "add" }).click();

    const playwrightRequest0: Record<string, any> = {"description": "Logging plan"};

    await page.locator("#description").fill(getValue(playwrightRequest0, "description"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/nutritionplan/**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(201);
    const createdPlan0 = await response0.json();
    expect(createdPlan0.description).toBe("Logging plan");
    expect(createdPlan0.only_logging).toBe(true);
    expect(createdPlan0.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "add" }).click();

    const playwrightRequest1: Record<string, any> = {"description": "Planning draft"};

    await page.locator("#description").fill(getValue(playwrightRequest1, "description"));
    await page.getByRole("switch", { name: "Only track calories. Check" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v2/nutritionplan/**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response1 = await responsePromise1;

    expect(response1.status()).toBe(201);
    const createdPlan1 = await response1.json();
    expect(createdPlan1.description).toBe("Planning draft");
    expect(createdPlan1.only_logging).toBe(false);
    expect(createdPlan1.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("link", { name: "Planning draft" })).toBeVisible();
    await expect(page.getByRole("link")).toHaveCount(2);
    await page.getByRole("switch", { name: "Only plans used for logging" }).click();
    await expect(page.getByRole("link")).toHaveCount(1);
    await expect(page.getByRole("link", { name: "Logging plan" })).toContainText("Logging plan");
    await expect(page.getByRole("link", { name: "Planning draft" })).toHaveCount(0);
    await expect(page.getByRole("switch", { name: "Only plans used for logging" })).toBeChecked();
    await page.getByRole("switch", { name: "Only plans used for logging" }).click();
    await expect(page.getByRole("link")).toHaveCount(2);
    await expect(page.getByRole("link", { name: "Planning draft" })).toBeVisible();
});
