// Generated by Skyramp v1.3.40 on 2026-08-28 23:02:00.907724 -0700 PDT m=+1124.446864043
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output nutrition_ingredient_search_renamed_endpoint.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/nutrition_ingredient_search_renamed_endpoint_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

// kept inline: index.ts — React component barrel re-exporting page components (About, AddExercise, Login, WeightOverview); defines no class, no locators and no Playwright actions, so it cannot cover any action in this test.

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// Test data
const uniqueSuffix = Date.now();
// PlanForm.tsx:44 caps the description at 25 characters, so the run-unique name must stay short.
const planDescription = "Plan " + String(uniqueSuffix).slice(-8);
const ingredientSearchTerm = "apple";

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(760000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => { pageErrors.push(error.message); });

    await page.goto(`${baseUrl}/en/dashboard`);
    await page.getByRole("button", { name: "Nutrition", exact: true }).click();
    await page.getByRole("menuitem", { name: "Overview" }).click();
    await page.keyboard.press("Escape");
    await page.getByRole("button", { name: "add", exact: true }).click();

    const playwrightRequest0: Record<string, any> = {"description": planDescription};

    await page.locator("#description").fill(getValue(playwrightRequest0, "description"));
    await page.getByRole("switch", { name: "Only track calories. Check" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/nutritionplan/**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(201);
    expect((await response0.json()).description).toBe(planDescription);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("link", { name: planDescription })).toHaveCount(1);
    await expect(page.getByRole("link", { name: planDescription })).toContainText(planDescription);
    await page.getByRole("link", { name: planDescription }).click();
    await page.getByRole("button", { name: "Add nutrition diary entry" }).click();

    // The three ingredient info calls read the shared ApiPath.INGREDIENTINFO_PATH
    // constant this PR repointed, so the search must reach ingredient-info and not
    // the retired ingredientinfo path, which answers 410.
    const ingredientSearchResponse = page.waitForResponse("**/api/v2/ingredient-info/**");
    await page.locator("#ingredient-autocomplete").fill(ingredientSearchTerm);
    const searchResponse = await ingredientSearchResponse;
    expect(searchResponse.status()).toBe(200);
    expect(searchResponse.url()).toContain("/api/v2/ingredient-info/");
    expect(searchResponse.url()).toContain(`name__search=${ingredientSearchTerm}`);

    await expect(page.getByRole("combobox", { name: "Search by ingredient name" })).toHaveValue(ingredientSearchTerm);
    await expect(page.getByText("No results")).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
