# Generated by Skyramp on 2026-08-29 05:51:49.406 Pacific Daylight Time


import skyramp
import os


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")


def get_ingredientinfo_list(client, headers, expected_status=410):
    # Execute Request
    response = client.send_request(
        url=URL_localhost,
        path="/api/v2/ingredientinfo/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert response.status_code == expected_status
    return response


def get_ingredientinfo_detail(client, headers, ingredient_id, expected_status=410):
    # Execute Request
    response = client.send_request(
        url=URL_localhost,
        path=f"/api/v2/ingredientinfo/{ingredient_id}/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert response.status_code == expected_status
    return response


def get_ingredient_info_list(client, headers, expected_status=200):
    # Execute Request
    response = client.send_request(
        url=URL_localhost,
        path="/api/v2/ingredient-info/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert response.status_code == expected_status
    return response
