# Generated by Skyramp on 2026-08-30 06:21:36.820 Pacific Daylight Time


import skyramp
import os


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")


def make_headers():
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


def get_weightentry_summary(client, headers, user=None, expected_status=200):
    query_params = {} if user is None else {"user": [user]}
    response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/summary/",
        method="GET",
        headers=headers,
        query_params=query_params
    )
    assert response.status_code == expected_status
    return response


def create_weightentry(client, headers, date="2026-01-15T10:00:00Z", weight=120, expected_status=201):
    request_body = r'''{
        "date": "2026-01-15T10:00:00Z",
        "weight": 120
    }'''
    response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/",
        method="POST",
        body=request_body,
        headers=headers,
        data_override={"date": date, "weight": weight}
    )
    assert response.status_code == expected_status
    return response


def delete_weightentry(client, headers, weightentry, expected_status=204):
    response = client.send_request(
        url=URL_localhost,
        path="/api/v2/weightentry/{weightentry}/",
        method="DELETE",
        headers=headers,
        path_params={"weightentry": weightentry}
    )
    assert response.status_code == expected_status
    return response
