# Generated by Skyramp on 2026-08-30 17:02:52.570 Pacific Daylight Time


import skyramp
import os


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")


def get_ingredient_info_list(client, headers, limit, expected_status=200):
    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/ingredient-info/",
        method="GET",
        headers=headers,
        query_params={"limit": [limit]}
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == expected_status

    return endpoint_1_GET_response


def get_ingredient_list(client, headers, limit, expected_status=200):
    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v2/ingredient/",
        method="GET",
        headers=headers,
        query_params={"limit": [limit]}
    )

    # Generated Assertions
    assert endpoint_2_GET_response.status_code == expected_status

    return endpoint_2_GET_response
