// Generated by Skyramp v1.3.40 on 2026-08-28 18:49:04.619387 -0700 PDT m=+609.594010168
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output trophies_detail_streak_category_chip.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/trophies_detail_streak_category_chip_trace.zip

// Import of required libraries
import { test, getBaseUrl, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// Test data
const streakTrophyName = "Unstoppable";
const sequenceTrophyName = "Weekend Warrior";
const countTrophyName = "Beginner";

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(773000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.goto(`${baseUrl}/en-us/trophies`);
    await page.waitForLoadState('networkidle');

    const trophyCards = page.locator('.MuiCard-root');
    const categoryChips = page.locator('.MuiChip-root');

    await trophyCards.first().waitFor({ state: 'visible', timeout: 10000 });

    await expect(page.getByRole('heading', { name: 'Trophies' })).toHaveText('Trophies');

    // Every trophy card carries exactly one category chip. A trophy_type with no
    // entry in TROPHY_TYPE_LABEL would leave its card without a resolved label,
    // so an unequal count is the signal that the label map fell behind the API.
    await expect(trophyCards).toHaveCount(20);
    await expect(categoryChips).toHaveCount(20);

    const streakCard = trophyCards.filter({ has: page.locator(`img[title="${streakTrophyName}"]`) });
    const sequenceCard = trophyCards.filter({ has: page.locator(`img[title="${sequenceTrophyName}"]`) });
    const countCard = trophyCards.filter({ has: page.locator(`img[title="${countTrophyName}"]`) });

    // The trophy this change reclassifies now reads Streak, not Sequence
    await expect(streakCard.locator('.MuiChip-label')).toHaveText('Streak');

    // The weekend trophy keeps the Sequence category it already had
    await expect(sequenceCard.locator('.MuiChip-label')).toHaveText('Sequence');

    // A third category proves the label is looked up per trophy, not hardcoded
    await expect(countCard.locator('.MuiChip-label')).toHaveText('Count');

    // The trophy image directory is derived from trophy_type, so reclassifying
    // the trophy moves its image path too
    await expect(streakCard.locator('img')).toHaveAttribute(
        'src',
        /\/static\/trophies\/streak\/[0-9a-f-]+\.png$/
    );

    expect(pageErrors).toHaveLength(0);
});
