# Generated by Skyramp v1.3.40 on 2026-08-28 19:57:10.977498 -0700 PDT m=+721.008582168
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output trophy_summary_total_matches_progress_grid_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp/scenario_trophy_summary_total_matches_progress_grid.json

# Import of required libraries
import skyramp
import json
import os
import time

from SkyrampUtils import get_trophy_progress, get_trophy_summary


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")


def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_2_GET_response = get_trophy_summary(client, URL_localhost, headers)

    # Generated Assertions
    assert skyramp.check_schema(endpoint_2_GET_response, r'''{"earned": 0, "total": 20}''')
    summary_earned = skyramp.get_response_value(endpoint_2_GET_response, "earned")
    summary_total = skyramp.get_response_value(endpoint_2_GET_response, "total")
    assert summary_earned == 0
    assert summary_earned <= summary_total

    # Execute Request
    endpoint_1_GET_response = get_trophy_progress(client, URL_localhost, headers)

    # Generated Assertions
    progress_count = len(json.loads(endpoint_1_GET_response.response_body))
    assert progress_count == 20
    assert skyramp.get_response_value(endpoint_1_GET_response, "0.trophy.id") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "0.is_earned") is False

    # The screen prints "<earned> of <total> trophies earned" directly above the
    # grid the progress endpoint fills, so the two must describe the same set
    assert summary_total == progress_count


if __name__ == "__main__":
    test_integration()
