// Generated by Skyramp v1.3.40 on 2026-08-29 22:21:43.909696 -0700 PDT m=+849.120685126
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output trophies_streak_category_chip.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/trophies_streak_category_chip_v2_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/login`);
    await page.goto(`${baseUrl}/en/trophies`);

    await expect(page.getByRole('heading', { name: 'Trophies' })).toHaveText('Trophies');

    const trophyCards = page.locator('.MuiCard-root');
    await expect(trophyCards).toHaveCount(20);

    const unstoppableCard = trophyCards.filter({ hasText: 'Maintain a 30-day workout streak' });
    await expect(unstoppableCard.locator('.MuiChip-label')).toHaveText('Streak');

    const weekendWarriorCard = trophyCards.filter({ hasText: 'Work out on Saturday and Sunday for 4 consecutive weekends' });
    await expect(weekendWarriorCard.locator('.MuiChip-label')).toHaveText('Sequence');

    const beginnerCard = trophyCards.filter({ hasText: 'Complete your first workout' });
    await expect(beginnerCard.locator('.MuiChip-label')).toHaveText('Count');

    expect(pageErrors).toHaveLength(0);
});
