// Generated by Skyramp v1.3.40 on 2026-08-29 23:51:10.067656 -0700 PDT m=+719.153534042
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output trophies_summary_count_matches_grid.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/trophies_summary_count_matches_grid_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1001000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/trophies`);
    await page.waitForLoadState("networkidle");
    await page.getByRole("img", { name: "Beginner" }).waitFor({ state: "visible", timeout: 10000 });

    await expect(page.getByRole("img", { name: "Beginner" })).toBeVisible();
    await expect(page.getByText("/ 1 workouts")).toContainText("0 / 1 workouts");
    await expect(page.getByText("Return to training after")).toContainText("Return to training after being inactive for 30 days");

    const trophyCardCount = await page.getByRole("img", { name: /.+/ }).count();
    expect(trophyCardCount).toBe(20);

    await expect(page.getByText(/of \d+ trophies earned/)).toHaveText(`0 of ${trophyCardCount} trophies earned`);
});
