# Generated by Skyramp v1.3.40 on 2026-08-29 23:48:18.775745 -0700 PDT m=+547.861858917
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output trophy_summary_matches_visible_list_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp/scenario_trophy_summary_matches_visible_list.json

# Import of required libraries
import skyramp
import os
import time

from SkyrampUtils import get_trophy_list, get_trophy_summary


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")


def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    endpoint_2_GET_response = get_trophy_summary(client, headers)

    assert skyramp.check_schema(endpoint_2_GET_response, r'''{"earned": 0, "total": 21}''')
    assert skyramp.get_response_value(endpoint_2_GET_response, "earned") >= 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "total") >= 0
    assert skyramp.get_response_value(endpoint_2_GET_response, "earned") <= skyramp.get_response_value(endpoint_2_GET_response, "total")

    endpoint_1_GET_response = get_trophy_list(client, headers, limit="100")

    assert skyramp.check_schema(endpoint_1_GET_response, r'''{"count": 21, "next": null, "previous": null, "results": [{"id": 1, "uuid": "9f1c7c7e-3b2a-4b6f-9b5f-1c3e2d4f5a60", "name": "Beginner", "description": "Complete your first workout", "image": "http://localhost:8000/static/trophies/count/9f1c7c7e-3b2a-4b6f-9b5f-1c3e2d4f5a60.png", "trophy_type": "count", "is_hidden": false, "is_progressive": true, "is_repeatable": false, "order": 1}]}''')
    assert skyramp.get_response_value(endpoint_1_GET_response, "next") is None
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") <= 100
    assert skyramp.get_response_value(endpoint_2_GET_response, "total") == skyramp.get_response_value(endpoint_1_GET_response, "count")


if __name__ == "__main__":
    test_integration()
