# Generated by Skyramp v1.3.40 on 2026-08-28 19:57:00.552802 -0700 PDT m=+710.583931459
# Command: skyramp generate contract rest http://localhost:8000/api/v2/trophy/summary/ \
# 		--api-schema http://localhost:8000/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--provider-output trophy_summary_contract_test.py \
# 		--response-data {"earned":0,"total":21} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os

from SkyrampUtils import get_trophy_summary


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v2/trophy/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_summary_GET_response_body = r'''{
        "earned": 0,
        "total": 21
    }'''

    # Execute Request
    summary_GET_response = get_trophy_summary(client, URL, headers)

    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.check_schema(summary_GET_response, expected_summary_GET_response_body)
    assert skyramp.get_response_value(summary_GET_response, "earned") == 0
    assert skyramp.get_response_value(summary_GET_response, "total") == 21
    assert skyramp.get_response_value(summary_GET_response, "earned") <= skyramp.get_response_value(summary_GET_response, "total")
    assert skyramp.get_response_value(summary_GET_response, "name") is None
    assert skyramp.get_response_value(summary_GET_response, "uuid") is None
    assert skyramp.get_response_value(summary_GET_response, "trophy_type") is None


if __name__ == "__main__":
    test_summary_get()
