// Generated by Skyramp v1.3.40 on 2026-08-28 20:04:16.153625 -0700 PDT m=+1146.227501876
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output trophies_screen_earned_count_line.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/trophies_screen_earned_count_line_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1495000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(`${baseUrl}/en/trophies`);
    await expect(page.getByText("of 21 trophies earned")).toContainText("0 of 21 trophies earned");
    await expect(page.getByText("Beginner", { exact: true })).toHaveText("Beginner");
    await expect(page.getByText("Phoenix", { exact: true })).toHaveText("Phoenix");
});
