// Generated by Skyramp v1.3.40 on 2026-08-29 23:24:25.225725 -0700 PDT m=+934.437867960
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_summary_strip_figures.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_summary_strip_figures_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1411000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(`${baseUrl}/en/weight/overview`);
    await expect(page.getByRole("heading", { name: "3", exact: true })).toHaveText("3");
    await expect(page.getByRole("heading", { name: "81.2", exact: true })).toHaveText("81.2");
    await expect(page.getByRole("heading", { name: "80.5", exact: true })).toHaveText("80.5");
    await expect(page.getByRole("heading", { name: "81.9", exact: true })).toHaveText("81.9");
    await expect(page.getByText("1–3 of")).toContainText("1–3 of 3");
    await page.getByRole("button", { name: "All" }).click();
    await expect(page.getByRole("heading", { name: "3", exact: true })).toHaveText("3");
    await expect(page.getByRole("heading", { name: "81.2", exact: true })).toHaveText("81.2");
    await expect(page.getByRole("heading", { name: "80.5", exact: true })).toHaveText("80.5");
    await expect(page.getByRole("heading", { name: "81.9", exact: true })).toHaveText("81.9");
    await expect(page.getByText("1–3 of")).toContainText("1–3 of 3");
    await expect(page.getByRole("row")).toHaveCount(4);
});
