// Generated by Skyramp v1.3.40 on 2026-08-29 21:53:33.981137 -0700 PDT m=+1991.536165876
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_entry_add_note_shows_in_table.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_entry_add_note_shows_in_table_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(103000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);

    // count() does not auto-wait, so let the grid render its first data row first
    await page.getByRole("row").nth(1).waitFor({ state: "visible" });
    const rowCountBefore = await page.getByRole("row").count();

    await page.getByRole("button", { name: "add" }).nth(1).click();

    const playwrightRequest0: Record<string, any> = {
        "notes": "weighed after breakfast",
        "weight": "82.4"
    };

    await page.locator("#weight").fill(getValue(playwrightRequest0, "weight"));
    await page.locator("#notes").fill(getValue(playwrightRequest0, "notes"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/weightentry/**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The entry was created and the API stored the note exactly as typed
    expect(response0.status()).toBe(201);
    const body0 = await response0.json();
    expect(body0.notes).toBe(getValue(playwrightRequest0, "notes"));
    expect(body0.weight).toBe("82.40");
    expect(body0.id).toBeGreaterThan(0);

    // The form dates the entry "now", so the new row sorts to the top of the table.
    // Row 0 is the header, so row 1 is the entry that was just created.
    const newRow = page.getByRole("row").nth(1);
    await expect(newRow).toContainText(getValue(playwrightRequest0, "notes"));
    await expect(newRow).toContainText(getValue(playwrightRequest0, "weight"));

    // exactly one row was added — catches a create that writes twice
    expect(await page.getByRole("row").count()).toBe(rowCountBefore + 1);
});
