# Generated by Skyramp v1.3.40 on 2026-08-29 23:21:07.097422 -0700 PDT m=+736.309858960
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weight_summary_reflects_new_entry_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp/scenario_weight_summary_reflects_new_entry.json

# Import of required libraries
import skyramp


from SkyrampUtils import (
    create_weightentry,
    delete_weightentry,
    get_weightentry_summary,
    make_headers,
)


def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    headers = make_headers()

    # The aggregate before the mutation.
    endpoint_2_GET_response = get_weightentry_summary(client, headers)

    # Generated Assertions
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") == 3
    assert skyramp.get_response_value(endpoint_2_GET_response, "min_weight") == 80.5
    assert skyramp.get_response_value(endpoint_2_GET_response, "max_weight") == 81.9

    # A weight entry heavier than every existing one.
    endpoint_1_POST_response = create_weightentry(
        client, headers, date="2026-01-15T10:00:00Z", weight=120
    )

    # Generated Assertions
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "120.00"
    assert "2026-01-15" in skyramp.get_response_value(endpoint_1_POST_response, "date")
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # The aggregate must now count the new entry and report the new maximum.
    endpoint_2_GET_1_response = get_weightentry_summary(client, headers)

    # Generated Assertions
    # The aggregate is recomputed over the entry set, so the new row must move
    # both the count and the maximum.
    assert skyramp.get_response_value(endpoint_2_GET_1_response, "count") == \
        skyramp.get_response_value(endpoint_2_GET_response, "count") + 1
    assert skyramp.get_response_value(endpoint_2_GET_1_response, "max_weight") == 120.0
    assert skyramp.get_response_value(endpoint_2_GET_1_response, "min_weight") == \
        skyramp.get_response_value(endpoint_2_GET_response, "min_weight")

    # Remove the entry so the aggregate returns to its seeded state.
    endpoint_3_DELETE_response = delete_weightentry(
        client,
        headers,
        weightentry=skyramp.get_response_value(endpoint_1_POST_response, "id"),
    )

    # The aggregate must recompute after the delete, not serve the four-entry
    # figures.
    endpoint_2_GET_2_response = get_weightentry_summary(client, headers)

    # Generated Assertions
    # Removing the row must put every aggregate back where it started - a stale
    # count or maximum here means the summary is not recomputed on read.
    assert skyramp.get_response_value(endpoint_2_GET_2_response, "count") == \
        skyramp.get_response_value(endpoint_2_GET_response, "count")
    assert skyramp.get_response_value(endpoint_2_GET_2_response, "max_weight") == \
        skyramp.get_response_value(endpoint_2_GET_response, "max_weight")
    assert skyramp.get_response_value(endpoint_2_GET_2_response, "min_weight") == \
        skyramp.get_response_value(endpoint_2_GET_response, "min_weight")


if __name__ == "__main__":
    test_integration()
