// Generated by Skyramp v1.3.40 on 2026-08-28 16:54:06.530612 -0700 PDT m=+1461.915740792
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_overview_survives_api_error.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_overview_survives_api_error_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

// kept inline: index.ts — it re-exports the app's React page components (About, WeightOverview, ...), not Playwright page objects, so it exposes no locators or actions this test can call.

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

// assertions reviewed: the response-body rules do not apply here - this test issues no
// sendRequest and holds no response object, so there is no status code or JSON path to assert.
// What it can observe is render state, and that is what it checks: the Weight heading, the
// Notes column header, the first data row, and that row's Notes cell. Together they fail on
// the blank screen the page renders when the weight query errors, which is the point of the test.
test('testUi', async ({ page }) => {
    test.setTimeout(939000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    // When the weight query fails, this screen renders nothing at all rather than an error,
    // so these checks are what separates a loaded page from a blank one.
    await expect(page.getByRole("heading", { name: "Weight" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Notes" })).toBeVisible();

    const dataRows = page.locator('[role="row"][data-id]');
    await expect(dataRows.first()).toBeVisible();

    // Every row exposes a Notes cell, whether or not the entry carries a note
    await expect(dataRows.first().locator('[data-field="notes"]')).toHaveCount(1);
});
