// Generated by Skyramp v1.3.40 on 2026-08-28 16:54:11.402479 -0700 PDT m=+1466.787585167
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_table_inline_note_over_limit.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_table_inline_note_over_limit_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// 101 characters - one past the max_length=100 the notes column declares
const overLimitNote = "OVER-LIMIT-NOTE-" + "x".repeat(85);

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1106000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);

    // Address the newest entry by position, so the test does not depend on a particular seeded date
    const firstRow = page.locator('[role="row"][data-id]').first();
    const firstRowNotes = firstRow.locator('[data-field="notes"]');

    await firstRow.getByLabel("Edit").click();

    const playwrightRequest0: Record<string, any> = {"notes": overLimitNote};

    await firstRowNotes.locator("input").fill(getValue(playwrightRequest0, "notes"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/weightentry/**/**");
    await firstRow.getByRole("menuitem", { name: "Save" }).click();
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(400);
    expect((await response0.json()).notes[0]).toBe("Ensure this field has no more than 100 characters.");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The grid must not keep a value the API refused, whatever the note held beforehand
    await expect(firstRowNotes).not.toHaveText(overLimitNote);

    await firstRow.getByLabel("Edit").click();

    const playwrightRequest1: Record<string, any> = {"notes": "after holidays"};

    await firstRowNotes.locator("input").fill(getValue(playwrightRequest1, "notes"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v2/weightentry/**/**");
    await firstRow.getByRole("menuitem", { name: "Save" }).click();
    const response1 = await responsePromise1;

    expect(response1.status()).toBe(200);
    expect((await response1.json()).notes).toBe("after holidays");

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(firstRowNotes).toHaveText("after holidays");

    await firstRow.getByLabel("Edit").click();

    const playwrightRequest2: Record<string, any> = {"notes": overLimitNote};

    await firstRowNotes.locator("input").fill(getValue(playwrightRequest2, "notes"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v2/weightentry/**/**");
    await firstRow.getByRole("menuitem", { name: "Save" }).click();
    const response2 = await responsePromise2;

    expect(response2.status()).toBe(400);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // A refused edit must leave the note that was already accepted intact
    await expect(firstRowNotes).toHaveText("after holidays");
});
