// Generated by Skyramp v1.3.40 on 2026-08-28 22:03:36.747393 -0700 PDT m=+638.405397376
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_summary_strip_renders_figures.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_summary_strip_renders_figures_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(548000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    // The summary values are h6 headings; the same numbers also appear as table
    // cells, so the heading role is what makes each locator unambiguous.
    await expect(page.getByRole("heading", { name: "3", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "81.2", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "80.5", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "81.9", exact: true })).toBeVisible();

    // The four figures are the aggregates of the entries the table lists below them
    await expect(page.getByText("1–3 of")).toContainText("1–3 of 3");
});
