# Generated by Skyramp v1.3.40 on 2026-08-29 23:21:01.887451 -0700 PDT m=+731.099896501
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output weight_summary_user_param_unvalidated_integration_test.py \
# 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp/scenario_weight_summary_user_param_unvalidated.json

# Import of required libraries
import skyramp


from SkyrampUtils import get_weightentry_summary, make_headers


def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    headers = make_headers()

    # Declaration of variables
    user = "abc"

    # The caller's own summary: no user id, so get_queryset() scopes the
    # aggregate to the authenticated user.
    endpoint_1_GET_response = get_weightentry_summary(client, headers)

    # Generated Assertions
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 3
    assert skyramp.get_response_value(endpoint_1_GET_response, "min_weight") == 80.5
    assert skyramp.get_response_value(endpoint_1_GET_response, "max_weight") == 81.9
    assert round(skyramp.get_response_value(endpoint_1_GET_response, "avg_weight"), 4) == 81.2

    # Another member's summary. The ?user= branch swaps in
    # WeightEntry.objects.filter(user_id=user_id), which bypasses
    # get_queryset() - the only place that scopes entries to request.user.
    endpoint_1_GET_1_response = get_weightentry_summary(client, headers, user="2")

    # Generated Assertions
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "count") == 3
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "min_weight") == 70.0
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "max_weight") == 71.1
    assert round(skyramp.get_response_value(endpoint_1_GET_1_response, "avg_weight"), 4) == 70.5667

    # The figures belong to the other member, not the caller: ?user= really did
    # swap the queryset rather than being ignored.
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "min_weight") != \
        skyramp.get_response_value(endpoint_1_GET_response, "min_weight")
    assert skyramp.get_response_value(endpoint_1_GET_1_response, "max_weight") != \
        skyramp.get_response_value(endpoint_1_GET_response, "max_weight")

    # The parameter is documented as OpenApiTypes.INT, but the raw query string
    # goes straight into filter(user_id=...). A non-integer must be rejected
    # with 400, not raise an unhandled ValueError.
    endpoint_1_GET_2_response = get_weightentry_summary(
        client, headers, user="abc", expected_status=400
    )

    # Generated Assertions
    # A rejected query parameter must come back as a client error the caller can
    # read, not as an unhandled server exception.
    assert endpoint_1_GET_2_response.status_code < 500


if __name__ == "__main__":
    test_integration()
