// Generated by Skyramp v1.3.40 on 2026-08-28 22:03:41.597237 -0700 PDT m=+643.255219626
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_summary_ignores_active_filter.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_summary_ignores_active_filter_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(101000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);
    await page.waitForSelector("text=Maximum");
    await page.getByRole("button", { name: "Last Week" }).click();
    await page.waitForTimeout(5000);

    /*
     * Last Week keeps only the entries dated within the past 7 days. The seed
     * places one entry 8 days back, so the table drops to 2 rows (3 role=row
     * elements: the header row carries role=row too).
     */
    await expect(page.getByText("1–2 of")).toContainText("1–2 of 2");
    await expect(page.getByRole("row")).toHaveCount(3);

    /*
     * The strip must describe the same entries the table shows. It does not:
     * BodyWeight.tsx renders <WeightSummary /> with no filter, and
     * useWeightSummaryQuery takes no filter argument, so the summary request
     * never carries date__gte and keeps aggregating every entry.
     */
    await expect(page.getByRole("heading", { name: "2", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "80.5", exact: true })).toHaveCount(0);
});
