// Generated by Skyramp v1.3.40 on 2026-08-28 22:03:45.778147 -0700 PDT m=+647.436110751
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_summary_survives_entry_deletion.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_summary_survives_entry_deletion_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(271000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);
    await page.waitForLoadState('networkidle');

    // The summary strip and the table both render before the row is clickable
    await page.getByRole("heading", { name: "3", exact: true }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("row", { name: "/21/2026, 5:00 AM 80.5 0 0 0" }).waitFor({ state: 'visible', timeout: 10000 });

    await page.getByRole("row", { name: "/21/2026, 5:00 AM 80.5 0 0 0" }).getByLabel("Delete").click();
    await page.waitForTimeout(5000);

    // The delete landed: the table drops from 3 rows to 2
    await expect(page.getByText("1–2 of")).toContainText("1–2 of 2");

    /*
     * The summary strip must describe the entries that remain. The deleted entry
     * weighed 80.5 kg and was the lightest, so the count becomes 2 and the
     * minimum becomes 81.2 — the lightest of the two survivors.
     */
    // 2 remaining rows plus the header row, which also carries role=row
    await expect(page.getByRole("row")).toHaveCount(3);

    await expect(page.getByRole("heading", { name: "2", exact: true })).toBeVisible();
    await expect(page.getByRole("heading", { name: "81.2", exact: true })).toBeVisible();

    /*
     * 80.5 was the deleted entry's weight. It must not survive anywhere on the
     * page — neither as a table cell nor as the summary's minimum.
     */
    await expect(page.getByRole("heading", { name: "80.5", exact: true })).toHaveCount(0);
    await expect(page.getByRole("gridcell", { name: "80.5", exact: true })).toHaveCount(0);
});
