// Generated by Skyramp v1.3.40 on 2026-08-28 16:54:15.665288 -0700 PDT m=+1471.050373834
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_form_add_entry_with_note.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_form_add_entry_with_note_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(174000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);

    const dataRows = page.locator('[role="row"][data-id]');
    await dataRows.first().waitFor({ state: 'visible', timeout: 10000 });
    const rowCountBefore = await dataRows.count();

    await page.getByRole("button", { name: "add" }).nth(1).click();

    const playwrightRequest0: Record<string, any> = {
        "notes": "back from the trip",
        "weight": "82.5"
    };

    await page.locator("#weight").fill(getValue(playwrightRequest0, "weight"));
    await page.locator("#notes").fill(getValue(playwrightRequest0, "notes"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/weightentry/**");
    await page.getByRole("button", { name: "Submit" }).click();
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(201);
    const created = await response0.json();
    // The note the form sent must come back on the created entry, not be dropped in transit
    expect(created.notes).toBe(getValue(playwrightRequest0, "notes"));
    expect(created.weight).toBe("82.50");
    expect(created.id).toBeGreaterThan(0);
    expect(created.date).toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The entry is dated now, and the grid sorts newest first, so it lands in the first row
    const newRow = dataRows.first();
    await expect(newRow.locator('[data-field="notes"]')).toHaveText("back from the trip");
    await expect(newRow.locator('[data-field="weight"]')).toHaveText("82.5");

    // Submitting the form adds exactly one entry
    await expect(dataRows).toHaveCount(rowCountBefore + 1);
});
