// Generated by Skyramp v1.3.40 on 2026-08-29 21:53:28.775356 -0700 PDT m=+1986.330395668
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_table_inline_edit_note.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_table_inline_edit_note_trace_2.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(586000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);

    // Target the row by its date only. The notes cell is what this test changes,
    // so including it in the locator would stop the test matching on a re-run.
    const targetRow = page.getByRole("row").filter({ hasText: "8/22/2026" });
    await targetRow.waitFor({ state: "visible" });
    const rowCountBefore = await page.getByRole("row").count();

    await targetRow.getByLabel("Edit").click();

    const playwrightRequest0: Record<string, any> = {"notes": "start of the cut"};

    await page.locator("input[type=\"text\"]").fill(getValue(playwrightRequest0, "notes"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/weightentry/**/**");
    await page.getByRole("menuitem", { name: "Save" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The PATCH that carried the note succeeded and echoed it back unchanged
    expect(response0.status()).toBe(200);
    const body0 = await response0.json();
    expect(body0.notes).toBe(getValue(playwrightRequest0, "notes"));
    expect(body0.weight).toBe("80.50");
    expect(body0.id).toBeGreaterThan(0);

    // ...and the saved note is what the table now shows for that row
    await expect(targetRow).toContainText("start of the cut");
    await expect(targetRow).toContainText("80.5");

    // editing a note must not add or drop a row
    expect(await page.getByRole("row").count()).toBe(rowCountBefore);
});
