// Generated by Skyramp v1.3.40 on 2026-08-29 21:53:38.386621 -0700 PDT m=+1995.941641334
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output weight_table_inline_edit_overlong_note.spec.ts \
// 		--output-dir /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /Users/mrugeshmaster/git/actions-runner/_work/wger-react/wger-react/.skyramp/weight_table_inline_edit_overlong_note_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(526000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/en/weight/overview`);

    // Target the row by its date only, so the locator does not depend on whatever
    // note the row happens to carry when the test starts.
    const targetRow = page.getByRole("row").filter({ hasText: "8/28/2026" });
    await targetRow.waitFor({ state: "visible" });
    const noteBefore = (await targetRow.textContent()) ?? "";
    const rowCountBefore = await page.getByRole("row").count();

    await targetRow.getByLabel("Edit").click();

    const playwrightRequest0: Record<string, any> = {"notes": "this note is deliberately one character over the hundred character limit that the backend enforces xx"};

    await page.locator("input[type=\"text\"]").fill(getValue(playwrightRequest0, "notes"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v2/weightentry/**/**");
    await page.getByRole("menuitem", { name: "Save" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The note is 101 characters, one over the model's max_length of 100,
    // so the API rejects the edit and names the offending field
    expect(response0.status()).toBe(400);
    const body0 = await response0.json();
    expect(body0.notes[0]).toBe("Ensure this field has no more than 100 characters.");
    expect(body0.notes[1]).toBeUndefined();

    // The rejected text must not be left sitting in the table as if it had saved
    await expect(targetRow).not.toContainText("this note is deliberately");
    await expect(targetRow).toContainText("81.9");
    expect(await targetRow.textContent()).toBe(noteBefore);

    // a rejected edit must not add or drop a row
    expect(await page.getByRole("row").count()).toBe(rowCountBefore);
});
